#!/bin/bash
#texts to be translated
#index.sh.htm
#Locale
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=om-control-center
#
hi=$"Hi"
title=$"OpenMandriva Control Center"
#Name=$"OpenMandriva Control Center"
#sections menu
menuindex=$"Welcome"
menusw=$"Software"
menuhardware=$"Hardware"
menuhardware2=$"Devices Configuration"
menulocaldisk=$"Local Disk configuration"
menunetwork=$"Networks"
menushare=$"Network Sharing"
menunetserv=$"Network servers"
menusystem=$"System"
menudesktop=$"Desktop"
menusecurity=$"Security"
menuabout=$"About"
#
#section presentation text
text=$"OpenMandriva Control Center is a set of tools to help you to configure your system, in each its part.
All in the same place and in the easiest way possible: <br/>
In each section you will find the programs to configure: <br/>
- Software Management<br/>
- Devices, Local Disks and Partition Manager<br/>
- Network and Internet<br/>
- System Configuration<br/>
- System Security<br/>
- and other parts of your system.<br/>"
# OpenMandriva Control Center
# Sections and sub-Sections
#
#
#section 01 sw-management
titlepage01=$"Software and media management"
#01-Install & Remove software
titlednfdragora=$"Install applications with dnfdragora"
descdnfdragora=$"Find and install applications"
#01-Edit media Sources
titleenrestrict=$"Add restricted"
descenrestrict=$"Enable restricted repository"
titleremrestrict=$"Remove restricted"
descremrestrict=$"Disable restricted repository"
titleenunsupported=$"Add unsupported"
descenunsupported=$"Enable unsupported repository"
titleremunsupported=$"Remove unsupported"
descremunsupported=$"Disable unsupported repository"
titleennonfree=$"Add non-free"
descennonfree=$"Enable non-free repository"
titleremnonfree=$"Remove non-free"
descremnonfree=$"Disable non-free repository"
titlerepopicker=$"OpenMandriva repo-picker"
descrepopicker=$"Enable and disable repositories the easy way"
#
#01-KBackup
titlekbackup=$"KBackup"
desckbackup=$"Backup your data with an easy to use user interface"
titlekdiskfree=$"Storage Devices"
desckdiskfree=$"Shows the disk usage of the mounted devices"
#
#section 02 Hardware
titlepage02=$"Devices Configurations"
#02-Configure video
titlexfdrake=$"Display and Monitor"
descxfdrake=$"Manage and configure monitor and display"
#02-Configure printer
titleconfigprint=$"Configure your printer"
descconfigprint=$"Configure your printer, add drivers for HP, EPSON, etc"
titlebluetooth=$"Bluetooth"
descbluetooth=$"Start and enable bluetooth service"
#
#section 02B local Disk configuration
titlepage06=$"Local Disk Configurations"
#02B-disk management
titlediskdrake=$"Configure your local drives"
descdiskdrake=$"Change, configure and manage your local drives";
titleaudio=$"Audio Volume"
descaudio=$"Configure Audio"
#
#section 03 Networks
titlepage03=$"Networks Configurations"
#03-Configure LAN
titleconfiglan=$"Connections"
descconfiglan=$"Edit your Network Connections"
#
#section 04 System Configurations
titlepage04=$"System Configurations"
#04-Add & Configure user and groups
titledrakuser=$"Add & Configure user and groups"
descdrakuser=$"Here you can configure new users add groups etc"
#04-Services management
titleservices=$"Services management"
descservices=$"Start and stop of the entire services available on the system"
#04-Add fonts
titledrakfont=$"Fonts"
descdrakfont=$"Font management or install new fonts"
#04-Configure time
titledrakclock=$"Configure time"
descdrakclock=$"Change time, configure the nts"
#
#04-Configure Keyboard
titlekeyboard=$"Configure keyboard"
desckeyboard=$"Change or configure keyboard layout"
#
#04-Configure Touchpad
titletouchpad=$"Configure touchpad"
desctouchpad=$"Configure touchpad input device"
#04-Other
titlexguest=$"Install Guest Account"
descxguest=$"Creates xguest user as a locked down user"
titlednfdrake=$"Install applications with DnfDrake"
descdnfdrake=$"Find and install applications with DnfDrake, and much more"
titleombugreport=$"Bug report tool"
descombugreport=$"The simple shell script will help in bug fixing process. The file generated should be attached to any bugreport"
titlediscover=$"Install Discover"
descdiscover=$"Plasma 5 package manager"
#
#04-Themes management
titlechangethemes=$"Desktop Themes"
descchangethemes=$"Change or install your favorite Plasma theme"
#04-Change icons theme
titlechangeicons=$"Desktop Icons"
descchangeicons=$"Change or install your favorite icons theme"
#04-boot configuration
titleconfigboot=$"Configure the system boot"
descconfigboot=$"If you need to change the boot order of the system or repair grub2 manually or later add another operating system"
#
#section 05 Security
titlepage07=$"Security Configurations"
#05-Security management
titlefirewall=$"Configure your firewall"
descfirewall=$"Set up a firewall and monitor network connections";
#05-firewall applet
titlefirewall2=$"Open your firewall applet"
descfirewall2=$"Change, configure and manage your firewall settings from the applet";
#05-Keys
titlekeys=$"Passwords and Keys"
desckeys=$"Manage your passwords and encryption keys"
#
#About.sh.htm
about=$"About "
license=$"This software is licensed under the GNU General Public License version 2 (GPLv2)."
dependency=$"It uses Qt5 WebEngine and htmlscript."
bugs=$"For bugs, suggestions and improvements, please head to "
endapp=$"Exit"
#Additional
you_are_using=$"You are using"
with_kernel=$"with kernel"
arch=$"architecture"
next=$"Next"

