#!/bin/bash
if rpm -q discover &>/dev/null; then 
	kdialog --title $"OpenMandriva" --msgbox $"Discover is already installed."
else 
	kdesu -- dnf install --assumeyes discover discover-backend-packagekit
	if rpm -q discover-backend-packagekit &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
